### ISSUE TITLE
Geo Location editor issue 1

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#15]
When typing the geo-location of an asset, the asset gets rotated.
You can test by opening any asset and typing in any latitude/longitude in the text field.

**Comment by 3DGISKing** [comment]
fixed. please check.

**Comment by outsider787** [comment]
I still see the model rotated when I edit the lat/long fields
![image](https://user-images.githubusercontent.com/13057505/76627427-61ed1c00-6511-11ea-8922-fb6bcb1e5ac5.png)
