### ISSUE TITLE
New user disk quota

### ISSUE THREAD

**Issue by outsider787** [outsider787/gw3_construkted#9]
Currently when a new user signs up, they are have 0 GB upload quota.

Change the quota for new users to 2 GB

**Comment by 3DGISKing** [comment]
fixed

**Comment by outsider787** [comment]
Not fixed.
I just created a new account and tried to upload an asset.
I am showing 0GB on the frontend upload page
![image](https://user-images.githubusercontent.com/13057505/75369688-e98c2700-5891-11ea-9a48-8cd0bddfad89.png)
And I'm showing 0 GB on the https://gw3.construkted.com/profile/?active_tab=posts page
![image](https://user-images.githubusercontent.com/13057505/75369769-0d4f6d00-5892-11ea-8973-ab7b17e25887.png)

**Comment by 3DGISKing** [comment]
Sorry. Please recheck
